### ISSUE TITLE
Error when loading GAIA dataset in tutorial

### ISSUE THREAD

**Issue by EGaraldi** [cbyrohl/scida#101]
When loading GAIA dataset I get the following errors
INFO:scida.interfaces.mixins.units:Cannot parse unit string 'electron'.s**-1' from metadata description. Skipping.
INFO:scida.interfaces.mixins.units:Cannot parse unit string 'mag' from metadata description. Skipping.
INFO:scida.interfaces.mixins.units:Cannot parse unit string 'electron'.s**-1' from metadata description. Skipping.
INFO:scida.interfaces.mixins.units:Cannot parse unit string 'mag' from metadata description. Skipping.
INFO:scida.interfaces.mixins.units:Cannot parse unit string 'electron'.s**-1' from metadata description. Skipping.
INFO:scida.interfaces.mixins.units:Cannot parse unit string 'mag' from metadata description. Skipping.

**Comment by cbyrohl** [comment]
This should just be info output (rather than an error; due to units that cannot be parsed by pint), in parts due to limited [logarithmic unit support](https://pint.readthedocs.io/en/stable/user/log_units.html) and unknown unit 'electron' (?), so we will have to think about how to handle this for now. I would keep the verbosity to make the user aware of limited units for these fields.

**Comment by EGaraldi** [comment]
I see. I think at the very least there should be a comment in the tutorial explaining this behavior is understood and expected for the dataset. Maybe the INFO can be made more explicit by saying something like "This unit will not be available" rather than just "Skipping"
