### ISSUE TITLE
Warning in derived fields example

### ISSUE THREAD

**Issue by kyleaoman** [cbyrohl/scida#115]
I get the following warning when running the examples in the 'derived fields' section of the docs:

```
>>> ds['stars']['VelMag']
/home/txwx36/.venv/scida/lib64/python3.11/site-packages/dask/array/core.py:3469: UserWarning: Passing an object to dask.array.from_array which is already a Dask collection. This can lead to unexpected behavior.
```

**Comment by cbyrohl** [comment]
This issue is related to pint. For xarray they discussed the same issue of pint interplay with dask: https://github.com/xarray-contrib/pint-xarray/issues/116 and https://github.com/pydata/xarray/issues/5559. Short-term, I will add this warning to the FAQ and/or suppress error. Long-term, need to check how xarray fixed this in this PR: https://github.com/pydata/xarray/pull/5571

**Comment by cbyrohl** [comment]
I adjusted the example to not produce this warning in #122
