### ISSUE TITLE
MCST units YAML

### ISSUE THREAD

**Issue by dnelson86** [cbyrohl/scida#183]
Can we add a config file to give (more) complete support for current MCST runs.

Matthew has filled in the majority of the units for the fields here: https://www.tng-project.org/w/index.php/MCST

Relevant for @jrspreng

**Comment by cbyrohl** [comment]
Could you double check the documented units for GrackleCoolTime and RadiationEnergyDensity? Is "kpc/h" really referring to physical units here (opposed to the explicit ckpc reference otherwise)?

Also, "IonizingPhotonRate1e49" should be renamed "IonizingPhotonRate" in future MCST simulation runs, when decorating with units, this only adds ambiguity when having an explicit unit reference in the name (one might think this implies an implicit 1e49 scaling, which is now taken care of by the unit annotations).

**Comment by dnelson86** [comment]
@mcsmithastro

**Comment by mcsmithastro** [comment]
GrackleCoolTime will come out in code time units, which is [length] / [velocity] and therefore, for the TNG unit system we are adopting here, (kpc/h) / (km/s). The little h parameters hang around regardless of whether it's a proper or comoving length, via the definition of All.UnitLength_in_cm (which actually is "factor to convert internal length unit to cm/h").

Likewise, RadiationEnergyDensity is proper code unit energy / volume. Again, factors of h have nothing to do with whether it's proper or comoving.

We can rename IonizingPhotonRate1e49 if you prefer. But my intention was that the name reminds us that this is an exception i.e. the units are not 1/code unit time. The reason for this is that a typical source will have a rate of ~10^(64 - 66) (km/s) / (kpc/h) which we can't put in a float32 if we write it out in single precision.

Regardless, I think hard coding the units is a really bad idea. You should interrogate them from the attributes attached to the units. Then you ever analyse a simulation with a different convention it will just automatically work it out. Worth noting that not everyone uses the TNG units system.

**Comment by dnelson86** [comment]
If unit metadata is present, it will be used. I think we are just discussing adding support for runs/fields without metadata, which is true of many current runs.

For clarification, in the wiki docs I have converted "kpc" to "pkpc" in GrackleCoolTime, RadiationEnergyDensity, and StellarLuminosity.
